<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="8" total="10" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-10T20:46:07 EET" name="Default suite" finished-at="2024-11-10T20:46:32 EET" duration-ms="25516">
    <groups>
    </groups>
    <test started-at="2024-11-10T20:46:07 EET" name="Default test" finished-at="2024-11-10T20:46:32 EET" duration-ms="25516">
      <class name="myTestcases">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:myTestcases@5911e990]" started-at="2024-11-10T20:46:07 EET" name="mySetup" finished-at="2024-11-10T20:46:09 EET" duration-ms="2117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="RandomlyChangeTheLanguage()[pri:8, instance:myTestcases@5911e990]" started-at="2024-11-10T20:46:09 EET" name="RandomlyChangeTheLanguage" finished-at="2024-11-10T20:46:15 EET" duration-ms="5636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RandomlyChangeTheLanguage -->
        <test-method signature="CheckTheSortOption()[pri:10, instance:myTestcases@5911e990]" started-at="2024-11-10T20:46:15 EET" name="CheckTheSortOption" finished-at="2024-11-10T20:46:32 EET" duration-ms="17740" status="FAIL">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: "Search"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: "Search"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:662)
at java.base/java.lang.Integer.parseInt(Integer.java:778)
at Parameters.SortOptionChecker(Parameters.java:62)
at myTestcases.CheckTheSortOption(myTestcases.java:145)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckTheSortOption -->
      </class> <!-- myTestcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
