<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="8" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-04T21:59:56 EET" name="Default suite" finished-at="2024-11-04T22:00:56 EET" duration-ms="60317">
    <groups>
    </groups>
    <test started-at="2024-11-04T21:59:56 EET" name="Default test" finished-at="2024-11-04T22:00:56 EET" duration-ms="60317">
      <class name="myTestcases">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:56 EET" name="mySetup" finished-at="2024-11-04T21:59:58 EET" duration-ms="1944" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="CheckTheEnglishLanguageIsDefault()[pri:1, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:58 EET" name="CheckTheEnglishLanguageIsDefault" finished-at="2024-11-04T21:59:58 EET" duration-ms="35" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckTheEnglishLanguageIsDefault -->
        <test-method signature="CheckTheDefaultCurrencyIsSAR()[pri:2, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:58 EET" name="CheckTheDefaultCurrencyIsSAR" finished-at="2024-11-04T21:59:58 EET" duration-ms="30" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckTheDefaultCurrencyIsSAR -->
        <test-method signature="CheckContactNumber()[pri:3, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:58 EET" name="CheckContactNumber" finished-at="2024-11-04T21:59:58 EET" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckContactNumber -->
        <test-method signature="CheckQitafLogoIsThereInTheFooter()[pri:4, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:58 EET" name="CheckQitafLogoIsThereInTheFooter" finished-at="2024-11-04T21:59:58 EET" duration-ms="45" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckQitafLogoIsThereInTheFooter -->
        <test-method signature="CheckHotelTabIsNotSelected()[pri:5, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:58 EET" name="CheckHotelTabIsNotSelected" finished-at="2024-11-04T21:59:58 EET" duration-ms="41" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckHotelTabIsNotSelected -->
        <test-method signature="CheckDepatureDate()[pri:6, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:58 EET" name="CheckDepatureDate" finished-at="2024-11-04T21:59:58 EET" duration-ms="34" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [5] but found [05]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [5] but found [05]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at myTestcases.CheckDepatureDate(myTestcases.java:106)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckDepatureDate -->
        <test-method signature="CheckReturnDate()[pri:7, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:58 EET" name="CheckReturnDate" finished-at="2024-11-04T21:59:58 EET" duration-ms="22" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [6] but found [06]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [6] but found [06]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at myTestcases.CheckReturnDate(myTestcases.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckReturnDate -->
        <test-method signature="RandomlyChangeTheLanguage()[pri:8, instance:myTestcases@72c28d64]" started-at="2024-11-04T21:59:58 EET" name="RandomlyChangeTheLanguage" finished-at="2024-11-04T22:00:39 EET" duration-ms="40431" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RandomlyChangeTheLanguage -->
        <test-method signature="CheckThatThePageIsFullyLoaded()[pri:9, instance:myTestcases@72c28d64]" started-at="2024-11-04T22:00:39 EET" name="CheckThatThePageIsFullyLoaded" finished-at="2024-11-04T22:00:39 EET" duration-ms="72" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckThatThePageIsFullyLoaded -->
        <test-method signature="CheckTheSortOption()[pri:10, instance:myTestcases@72c28d64]" started-at="2024-11-04T22:00:39 EET" name="CheckTheSortOption" finished-at="2024-11-04T22:00:56 EET" duration-ms="17612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckTheSortOption -->
      </class> <!-- myTestcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
